#!/bin/bash
# Тест Keepalive Spam Fix - Перевіряємо що консоль НЕ спамиться

echo "🧪 Testing Keepalive Console Spam Fix..."
echo "=========================================="
echo ""
echo "📋 Test Steps:"
echo "1. Відкрити http://localhost:5001 в браузері"
echo "2. Відкрити DevTools Console (F12)"
echo "3. Відправити запит 'Привіт'"
echo "4. Дочекатись відповіді (може зайняти ~10-30 секунд)"
echo ""
echo "✅ Expected Results:"
echo "   - Консоль НЕ має містити тисячі 'Failed to parse stream message'"
echo "   - Консоль НЕ має містити 'keepalive' повідомлення"
echo "   - Тільки нормальні ATLAS логи (CHAT, APP, TTS, ORCHESTRATOR)"
echo "   - DevTools працюють швидко, без лагів"
echo ""
echo "❌ If Failed:"
echo "   - Перевірити що виправлення в api-client.js застосовані"
echo "   - Переконатись що браузер cache очищений (Ctrl+Shift+R)"
echo "   - Подивитись чи orchestrator відправляє keepalive:"
echo "     tail -20 logs/orchestrator.log | grep keepalive"
echo ""
echo "🔍 Backend Check - Recent Orchestrator Logs:"
echo "-------------------------------------------"
tail -30 /Users/dev/Documents/GitHub/atlas4/logs/orchestrator.log | grep -E "(keepalive|stream|chat)" || echo "No relevant logs yet"
echo ""
echo "📊 System Status:"
./restart_system.sh status
echo ""
echo "🚀 Ready to test! Open http://localhost:5001 and check console."
