#!/bin/bash
# VAD & Conversation Loop Test Script
# Created: 2025-10-11 17:30

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║  VAD & Conversation Loop - Automated Test Instructions  ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
echo "🎯 Test Goals:"
echo "  1. Voice Activity Detection (VAD) works"
echo "  2. Conversation loop continues after TTS"
echo "  3. Transcription NOT empty"
echo "  4. Race condition fixed"
echo ""
echo "📋 Test Steps:"
echo ""
echo "1. Open http://localhost:5001 in browser"
echo ""
echo "2. Open Browser Console (F12 → Console)"
echo ""
echo "3. Hold microphone button for 2 seconds"
echo "   Expected: [CONVERSATION_MODE] 🎬 Activating conversation mode..."
echo ""
echo "4. Say 'Атлас'"
echo "   Expected: [WHISPER_KEYWORD] 🎯 KEYWORD DETECTED!"
echo ""
echo "5. Say any phrase (e.g., 'Привіт')"
echo "   Expected: [VAD: Speech started]"
echo ""
echo "6. ⚡ PAUSE for 1.5 seconds (CRITICAL TEST!)"
echo "   Expected: [VAD: Silence detected (1500ms) - triggering auto-stop]"
echo "             [Stopping recording (reason: silence)]"
echo ""
echo "7. Check transcription appears (NOT empty!)"
echo "   Expected: [Transcription successful: 'your text here']"
echo "             ⚠️ NOT: [Transcription completed but no text found]"
echo ""
echo "8. Atlas responds via TTS"
echo "   Expected: [TTS] Speaking for atlas..."
echo ""
echo "9. ⚡ After TTS completes (CRITICAL TEST!)"
echo "   Expected: [APP] 🔊 Emitting TTS_COMPLETED:"
echo "               isInConversation: true  ← MUST BE TRUE!"
echo "             [CONVERSATION] 🔊 Atlas finished speaking - starting continuous listening"
echo "             [MICROPHONE_BUTTON] Starting recording (trigger: conversation_continuous)"
echo ""
echo "10. Say another phrase WITHOUT 'Атлас'"
echo "    Expected: Recording starts automatically → VAD → transcription → repeat"
echo ""
echo "✅ SUCCESS CRITERIA:"
echo "   ✓ VAD auto-stops after 1.5 sec silence"
echo "   ✓ Transcription has text (NOT empty)"
echo "   ✓ isInConversation: true in TTS_COMPLETED"
echo "   ✓ Continuous recording starts after TTS"
echo "   ✓ NO 'Invalid state transition' errors"
echo ""
echo "❌ FAILURE INDICATORS:"
echo "   ✗ Recording waits full 6 seconds (VAD NOT working)"
echo "   ✗ 'Transcription completed but no text found'"
echo "   ✗ isInConversation: false in TTS_COMPLETED"
echo "   ✗ 'Conversation recording ignored - current state: X'"
echo "   ✗ Must say 'Атлас' again for next recording"
echo ""
echo "🔍 Debug Commands (Browser Console):"
echo ""
echo "// Check VAD state during recording"
echo "window.app.managers.voiceControl.services.get('microphone').mediaManager.vad?.getState()"
echo ""
echo "// Check conversation mode state"
echo "window.app.managers.conversationMode.isConversationActive()"
echo ""
echo "// Check microphone state"
echo "window.app.managers.voiceControl.services.get('microphone').currentState"
echo ""
echo "📊 Check logs:"
echo "tail -f logs/orchestrator.log | grep -E 'VAD|CONVERSATION|TTS_COMPLETED|Transcription'"
echo ""
echo "🚀 System ready at http://localhost:5001"
echo ""
