#!/bin/bash
# Test Conversation Loop - Manual Test Instructions
# Created: 2025-10-11 16:50

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║     CONVERSATION LOOP TEST - Manual Test Guide          ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
echo "📋 Test Steps:"
echo ""
echo "1. Open http://localhost:5001 in browser"
echo ""
echo "2. Open Browser Console (F12 → Console tab)"
echo ""
echo "3. Hold microphone button for 2 seconds → release"
echo "   Expected log: [CONVERSATION_MODE] 🎬 Activating conversation mode..."
echo ""
echo "4. Say 'Атлас' (wait for keyword detection)"
echo "   Expected log: [WHISPER_KEYWORD] 🎯 KEYWORD DETECTED! Атлас."
echo ""
echo "5. Say 'Привіт' (or any phrase)"
echo "   Expected: Transcription → Chat → Atlas responds via TTS"
echo ""
echo "6. ⚠️ CRITICAL: Wait for TTS to complete, then check logs:"
echo "   Expected log: [APP] 🔊 Emitting TTS_COMPLETED:"
echo "                   isInConversation: true  ← MUST BE TRUE!"
echo "                   conversationManager: true"
echo "                   conversationActive: true"
echo ""
echo "7. ⚠️ CRITICAL: Check if continuous listening started:"
echo "   Expected log: [CONVERSATION] 🔊 Atlas finished speaking (chat mode) - starting continuous listening"
echo "                 [CONVERSATION] 🔄 Starting continuous listening (no keyword needed)"
echo "                 [MICROPHONE_BUTTON] Starting recording (trigger: conversation_continuous)"
echo ""
echo "8. Say 'Розкажи анекдот' (WITHOUT saying 'Атлас'!)"
echo "   Expected: Recording → Transcription → Chat → Atlas responds → loop continues"
echo ""
echo "9. Wait 5 seconds in silence"
echo "   Expected: Auto-exit to keyword mode"
echo ""
echo "✅ SUCCESS CRITERIA:"
echo "   - isInConversation: true in TTS_COMPLETED event"
echo "   - Automatic continuous listening after TTS"
echo "   - Recording starts WITHOUT 'Атлас' keyword"
echo "   - Conversation loop cycles automatically"
echo ""
echo "❌ FAILURE INDICATORS:"
echo "   - isInConversation: false in TTS_COMPLETED"
echo "   - No continuous listening after TTS"
echo "   - Must say 'Атлас' again to record"
echo ""
echo "🔍 Debug Commands (paste in browser console):"
echo "   window.app.managers.conversationMode.isConversationActive()"
echo "   // Should return: true (when in conversation mode)"
echo ""
echo "📊 Check logs:"
echo "   tail -f logs/orchestrator.log | grep 'TTS_COMPLETED\\|CONVERSATION'"
echo ""
